### ISSUE TITLE
slow ndslice is weird

### ISSUE THREAD

**Issue by 9il** [dataPulverizer/KernelMatrixBenchmark#3]
With #2 ndslice has the same speed on my machine or it is a bit faster than custom matrix implementation.

Please provide the build command you are using to build a common D benchmark and Mir D benchmark. Looks like something has been missing.

**Comment by dataPulverizer** [comment]
I run with this:

```
dub run --compiler=ldc2 --build=release
```

This is the dub file:

https://github.com/dataPulverizer/KernelMatrixBenchmark/blob/master/ndslice/dub.json

I should have probably mentioned this performance difference to you before publishing but didn't think about it because the difference wasn't much. I just wanted to make sure that my basic matrix wasn't penalising D. Please let me know if there's a flag or a dub entry I'm missing.

**Comment by dataPulverizer** [comment]
Ah, just seen your pull request, taking a look at it now.

**Comment by dataPulverizer** [comment]
Actually once the benchmarks have finished and the plots are done I'll accept the PR and dump the .DS_Store file.

**Comment by dataPulverizer** [comment]
Accepted PR to update the ndslice code which now performs better than before.
